// What makes a checkout could not derive or partial beside a mirror this
// extractor can read: a call reaching an address outside the mirror convention
// entirely, any call at all found with no mirror to read it against, and the two
// constructs beside reflection and a string-keyed access this extractor records
// rather than passes over. Reaches no database.
package consumercontract_test

import (
	"strings"
	"testing"

	"github.com/dulguun0225/borg/factory/consumercontract"
)

// TestADirectNetworkCallOutsideTheMirrorConventionIsCouldNotDerive: a call into
// a network client package the checkout imports — detected by the callee's own
// import path, not by a name list, so an alias or an otherwise unlisted client
// package cannot pass silently — is could not derive for the whole consumer
// contract, naming the site, whatever its address argument is: a literal, a
// plain variable, a value read from a field, or anything else, none of which
// are traceable to a mirror's configured entry.
func TestADirectNetworkCallOutsideTheMirrorConventionIsCouldNotDerive(t *testing.T) {
	for name, of := range map[string]struct{ code string }{
		"a literal address": {code: `package main

import "net/http"

func call() {
	http.Get("https://producer.example/health")
}

func main() { call() }
`},
		"an address read from a field": {code: `package main

import "net/http"

type Config struct {
	URL string
}

func call(cfg Config) {
	http.Get(cfg.URL)
}

func main() {}
`},
		"a plain variable": {code: `package main

import "net/http"

func call(addr string) {
	http.Get(addr)
}

func main() { call("") }
`},
		"an unlisted client package": {code: `package main

import "net"

func call() {
	net.Dial("tcp", "producer.example:9000")
}

func main() { call() }
`},
	} {
		t.Run(name, func(t *testing.T) {
			d, _ := derived(t, checkout(t, map[string]string{"main.go": of.code}))
			if !d.CouldNotDerive() || d.Cause != consumercontract.CauseExtractionFailed || d.Reported == "" {
				t.Fatalf("%s derived %s, want could not derive naming the call site", name, d.Describe())
			}
		})
	}
}

// TestAnAddressArgumentIsCouldNotDeriveWhateverTheCalleesPackage: an address —
// a string literal shaped as a URL or host:port, or a value flowing from a
// store read or a configuration read — passed to a call outside the mirror
// convention is could not derive naming the site, whatever package the call
// reaches into; [ClientPackages] is kept only as a detector for a call with no
// such argument to trace.
func TestAnAddressArgumentIsCouldNotDeriveWhateverTheCalleesPackage(t *testing.T) {
	for name, of := range map[string]struct{ files map[string]string }{
		"a literal URL given to an unlisted client library": {files: map[string]string{
			"consumes.txt":                      "health producer health\n",
			consumercontract.FileName("health"): mirror,
			"main.go": `package main

import "github.com/example/sdk"

func call() {
	sdk.Connect("https://producer.example/health")
}

func main() { call() }
`,
		}},
		"a store-read address given to an unlisted client library": {files: map[string]string{
			"consumes.txt":                      "config self config store\n",
			consumercontract.FileName("config"): "package main\n\ntype Config struct {\n\tAddr string\n}\n",
			"main.go": `package main

import "github.com/example/sdk"

func call(c Config) {
	addr := c.Addr
	sdk.Connect(addr)
}

func main() {}
`,
		}},
	} {
		t.Run(name, func(t *testing.T) {
			d, _ := derived(t, checkout(t, of.files))
			if !d.CouldNotDerive() || d.Cause != consumercontract.CauseExtractionFailed || d.Reported == "" {
				t.Fatalf("%s derived %s, want could not derive naming the call site", name, d.Describe())
			}
		})
	}
}

// TestAServiceThatMakesAnyCallWithNoMirrorIsCouldNotDerive: a service whose file
// names no producer for an address it reaches is could not derive until its
// entries are authored, which is the state an adopted service arrives in — and
// that state is any call at all, absent a mirror to read it against.
func TestAServiceThatMakesAnyCallWithNoMirrorIsCouldNotDerive(t *testing.T) {
	dir := checkout(t, map[string]string{
		"main.go": `package main

import "fmt"

func main() { fmt.Println("hello") }
`,
	})
	d, _ := derived(t, dir)
	if !d.CouldNotDerive() || d.Reported == "" {
		t.Fatalf("a checkout that calls something with no mirror and no %s derived %s, want could not derive",
			consumercontract.ConfigurationFile, d.Describe())
	}
}

// generatedLikeFile carries the standard generated-file header, which this
// extractor reads as a file of accessors it cannot follow rather than a use of
// the mirror to scan for reads and writes.
const generatedLikeFile = `// Code generated by protoc-gen-go. DO NOT EDIT.
package main

type Generated struct {
	unexported int
}

func (g *Generated) GetStatus() string { return "" }
`

// TestAGeneratedFileIsAConstructTheExtractorCannotFollow: a generated accessor is
// one of the four constructs this extractor records rather than passes over.
func TestAGeneratedFileIsAConstructTheExtractorCannotFollow(t *testing.T) {
	dir := checkout(t, map[string]string{
		"consumes.txt":                      "health producer health\n",
		consumercontract.FileName("health"): mirror,
		"generated.pb.go":                   generatedLikeFile,
		"main.go": `package main

func report() {
	g := &Generated{}
	_ = g.GetStatus()
}

func main() { report() }
`,
	})
	d, _ := derived(t, dir)
	if !d.Partial() {
		t.Fatalf("the record is complete and the extractor met %d construct(s) it could not follow", len(d.Unfollowed))
	}
	found := false
	for _, u := range d.Unfollowed {
		if strings.Contains(u, "generated accessor") {
			found = true
		}
	}
	if !found {
		t.Fatalf("the unfollowed constructs are %v, want the generated file named", d.Unfollowed)
	}
}

// TestAMappingReadFromConfigurationIsAConstructTheExtractorCannotFollow: a
// mapping read from configuration is one of the four constructs this extractor
// records rather than passes over.
func TestAMappingReadFromConfigurationIsAConstructTheExtractorCannotFollow(t *testing.T) {
	dir := checkout(t, map[string]string{
		"consumes.txt":                      "health producer health\n",
		consumercontract.FileName("health"): mirror,
		"main.go": `package main

import "os"

func report(data map[string]string) {
	_ = data[os.Getenv("FIELD")]
}

func main() { report(nil) }
`,
	})
	d, _ := derived(t, dir)
	if !d.Partial() {
		t.Fatalf("the record is complete and the extractor met %d construct(s) it could not follow", len(d.Unfollowed))
	}
	found := false
	for _, u := range d.Unfollowed {
		if strings.Contains(u, "mapping read from configuration") {
			found = true
		}
	}
	if !found {
		t.Fatalf("the unfollowed constructs are %v, want the configuration mapping named", d.Unfollowed)
	}
}
